# Usar una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de la aplicación
COPY . .

# Instalar un servidor HTTP simple para servir la página
RUN npm install -g http-server

# Exponer el puerto 8080
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["http-server", "-p", "8080"]